dist: trusty
sudo: required
language: go
node_js: stable
go:
- 1.8.x
- master
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- nvm install stable
- node -v
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
- go get -u -v github.com/spf13/hugo
- yarn
env:
  matrix:
  - CMD=test
  - CMD=build
  - CMD=htmlvalidate
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=htmlvalidate
script:
- npm run $CMD
notifications:
  email: false
