sudo: false
language: node_js
node_js:
- stable
- 7
- 6
env:
  matrix:
  - CMD=test
  - CMD=build
  - CMD=htmlvalidate
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=htmlvalidate
script:
- npm run $CMD
notifications:
  email: false
