language: node_js
sudo: false
node_js:
- stable
- 6
- 5
go: master
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- go get -u -v github.com/spf13/hugo
notifications:
  email: false
