sudo: false
language: go
node_js: stable
go:
- 1.8.x
- master
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- go get -u -v github.com/spf13/hugo
- yarn
env:
  matrix:
  - CMD=test
  - CMD=eslint
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=eslint
script:
- npm run $CMD
notifications:
  email: false
