baseurl = "https://9renpoto.github.io"
languageCode = "ja-JP"
title = ":-)"
MetaDataFormat = "yaml"
enableGitInfo = true

[indexes]
  category = "categories"

[permalinks]
  blog = "blog/:year/:month/:day/:filename/"

[params]
  Links = ["profile", "slides"]
  GoogleTagManagerID = "GTM-TD87SR"
  MainTitle = ":-)"
  GithubID = "9renpoto"
  TwitterID = "9renpoto"
  FacebookID = "9renpoto"
  YoutubeID = "UCHkajp8KwHzG-88kcNoRAbw"
