baseurl = "https://9renpoto.github.io"
languageCode = "ja-JP"
title = ":-)"
MetaDataFormat = "yaml"

[indexes]
  category = "categories"

[permalinks]
  blog = "blog/:year/:month/:day/:filename/"

[params]
  Links = ["blog", "profile", "slides"]
  GithubID = "9renpoto"
  MainTitle = ":-)"
  TwitterID = "9renpoto"
  GoogleTagManagerID = "GTM-TD87SR"
